schema: "classroom50/repo-config/v1"
classroom: "pm-class"
assignment: "css-cv"
owner:
  username: "ryantornese"
  id: 165537403
  accepted_at: "2026-09-08T15:17:05Z"
source:
  owner: "CSCI4300-Web-Programming"
  owner_id: 212650580
  repo: "css-cv-template"
  branch: "main"
